source 'https://rubygems.org'

gem 'rails', '~> 8.1'
gem 'puma', '~> 8.0'
gem 'sqlite3', '~> 2.9'
gem 'omniauth_openid_connect', '~> 0.8'
gem 'json-jwt', '~> 1.17'
gem 'omniauth-rails_csrf_protection', '~> 2.0'
